import { ChapterListItemProp } from "../types/Chapter";

export const listOfChapters: ChapterListItemProp[] = [
  {
    chapterNumber: 1,
    name: "Al-Fatihah",
    arabicName: "الفاتحة",
    revelationType: "Meccan",
    numOfVerses: 7,
    translation: "The Opening",
  },
  {
    chapterNumber: 2,
    name: "Al-Baqarah",
    arabicName: "البقرة",
    revelationType: "Medinan",
    numOfVerses: 286,
    translation: "The Cow",
  },
  {
    chapterNumber: 3,
    name: "Aal-i-Imran",
    arabicName: "آل عمران",
    revelationType: "Medinan",
    numOfVerses: 200,
    translation: "The Family of Imran",
  },
  {
    chapterNumber: 4,
    name: "An-Nisa",
    arabicName: "النساء",
    revelationType: "Medinan",
    numOfVerses: 176,
    translation: "The Women",
  },
  {
    chapterNumber: 5,
    name: "Al-Ma'idah",
    arabicName: "المائدة",
    revelationType: "Medinan",
    numOfVerses: 120,
    translation: "The Table Spread",
  },
  {
    chapterNumber: 6,
    name: "Al-An'am",
    arabicName: "الأنعام",
    revelationType: "Meccan",
    numOfVerses: 165,
    translation: "The Cattle",
  },
  {
    chapterNumber: 7,
    name: "Al-A'raf",
    arabicName: "الأعراف",
    revelationType: "Meccan",
    numOfVerses: 206,
    translation: "The Heights",
  },
  {
    chapterNumber: 8,
    name: "Al-Anfal",
    arabicName: "الأنفال",
    revelationType: "Medinan",
    numOfVerses: 75,
    translation: "The Spoils of War",
  },
  {
    chapterNumber: 9,
    name: "At-Tawbah",
    arabicName: "التوبة",
    revelationType: "Medinan",
    numOfVerses: 129,
    translation: "The Repentance",
  },
  {
    chapterNumber: 10,
    name: "Yunus",
    arabicName: "يونس",
    revelationType: "Meccan",
    numOfVerses: 109,
    translation: "Jonah",
  },
  {
    chapterNumber: 11,
    name: "Hud",
    arabicName: "هود",
    revelationType: "Meccan",
    numOfVerses: 123,
    translation: "Hud",
  },
  {
    chapterNumber: 12,
    name: "Yusuf",
    arabicName: "يوسف",
    revelationType: "Meccan",
    numOfVerses: 111,
    translation: "Joseph",
  },
  {
    chapterNumber: 13,
    name: "Ar-Ra'd",
    arabicName: "الرعد",
    revelationType: "Medinan",
    numOfVerses: 43,
    translation: "The Thunder",
  },
  {
    chapterNumber: 14,
    name: "Ibrahim",
    arabicName: "إبراهيم",
    revelationType: "Meccan",
    numOfVerses: 52,
    translation: "Abraham",
  },
  {
    chapterNumber: 15,
    name: "Al-Hijr",
    arabicName: "الحجر",
    revelationType: "Meccan",
    numOfVerses: 99,
    translation: "The Rocky Tract",
  },
  {
    chapterNumber: 16,
    name: "An-Nahl",
    arabicName: "النحل",
    revelationType: "Meccan",
    numOfVerses: 128,
    translation: "The Bee",
  },
  {
    chapterNumber: 17,
    name: "Al-Isra",
    arabicName: "الإسراء",
    revelationType: "Meccan",
    numOfVerses: 111,
    translation: "The Night Journey",
  },
  {
    chapterNumber: 18,
    name: "Al-Kahf",
    arabicName: "الكهف",
    revelationType: "Meccan",
    numOfVerses: 110,
    translation: "The Cave",
  },
  {
    chapterNumber: 19,
    name: "Maryam",
    arabicName: "مريم",
    revelationType: "Meccan",
    numOfVerses: 98,
    translation: "Mary",
  },
  {
    chapterNumber: 20,
    name: "Ta-Ha",
    arabicName: "طه",
    revelationType: "Meccan",
    numOfVerses: 135,
    translation: "Ta-Ha",
  },
  {
    chapterNumber: 21,
    name: "Al-Anbiya",
    arabicName: "الأنبياء",
    revelationType: "Meccan",
    numOfVerses: 112,
    translation: "The Prophets",
  },
  {
    chapterNumber: 22,
    name: "Al-Hajj",
    arabicName: "الحج",
    revelationType: "Medinan",
    numOfVerses: 78,
    translation: "The Pilgrimage",
  },
  {
    chapterNumber: 23,
    name: "Al-Mu'minun",
    arabicName: "المؤمنون",
    revelationType: "Meccan",
    numOfVerses: 118,
    translation: "The Believers",
  },
  {
    chapterNumber: 24,
    name: "An-Nur",
    arabicName: "النور",
    revelationType: "Medinan",
    numOfVerses: 64,
    translation: "The Light",
  },
  {
    chapterNumber: 25,
    name: "Al-Furqan",
    arabicName: "الفرقان",
    revelationType: "Meccan",
    numOfVerses: 77,
    translation: "The Criterion",
  },
  {
    chapterNumber: 26,
    name: "Ash-Shu'ara",
    arabicName: "الشعراء",
    revelationType: "Meccan",
    numOfVerses: 227,
    translation: "The Poets",
  },
  {
    chapterNumber: 27,
    name: "An-Naml",
    arabicName: "النمل",
    revelationType: "Meccan",
    numOfVerses: 93,
    translation: "The Ant",
  },
  {
    chapterNumber: 28,
    name: "Al-Qasas",
    arabicName: "القصص",
    revelationType: "Meccan",
    numOfVerses: 88,
    translation: "The Stories",
  },
  {
    chapterNumber: 29,
    name: "Al-Ankabut",
    arabicName: "العنكبوت",
    revelationType: "Meccan",
    numOfVerses: 69,
    translation: "The Spider",
  },
  {
    chapterNumber: 30,
    name: "Ar-Rum",
    arabicName: "الروم",
    revelationType: "Meccan",
    numOfVerses: 60,
    translation: "The Romans",
  },
];
