import { WordInfo } from '../types/Word';

const arabicWordInfo: WordInfo[] = [
  {
    id: 0,
    word: 'بسم',
    translation: 'In the name',
    type: 'phrase',
    example: 'I begin in the name of God.',
  },
  {
    id: 1,
    word: 'الله',
    translation: 'The proper name of the one God',
    type: 'proper noun',
    example: 'Allah is the Creator of the heavens and the earth.',
  },
  {
    id: 2,
    word: 'الرحمن',
    translation: 'The Most Gracious, intensely merciful',
    type: 'noun',
    example: 'Allah is Ar-Rahman to all His creation.',
  },
  {
    id: 3,
    word: 'الرحيم',
    translation: 'The Most Merciful, especially merciful',
    type: 'noun',
    example: 'He is Ar-Rahim to the believers.',
  },
  {
    id: 4,
    word: 'الحمد',
    translation: 'All praise',
    type: 'noun',
    example: 'Al-hamdu belongs to Allah alone.',
  },
  {
    id: 5,
    word: 'لله',
    translation: 'Is for Allah',
    type: 'prepositional phrase',
    example: 'Al-hamdu lillaah.',
  },
  {
    id: 6,
    word: 'رب',
    translation: 'Lord, Sustainer',
    type: 'noun',
    example: 'Rabb of the worlds.',
  },
  {
    id: 7,
    word: 'العالمين',
    translation: 'Of the worlds, all beings',
    type: 'plural noun',
    example: 'The Lord of all creatures.',
  },
  {
    id: 8,
    word: 'الرحمن',
    translation: 'The Most Gracious, intensely merciful',
    type: 'noun',
    example: 'Mentioned again for emphasis.',
  },
  {
    id: 9,
    word: 'الرحيم',
    translation: 'The Most Merciful',
    type: 'noun',
    example: "Repeated to highlight Allah's mercy.",
  },
  {
    id: 10,
    word: 'مالك',
    translation: 'Master, Owner',
    type: 'noun',
    example: 'Malik of the Day of Judgement.',
  },
  {
    id: 11,
    word: 'يوم',
    translation: 'Day',
    type: 'noun',
    example: 'A reference to the Day of Judgement.',
  },
  {
    id: 12,
    word: 'الدين',
    translation: 'Of Judgement, Recompense',
    type: 'noun',
    example: 'The day when all will be recompensed.',
  },
  {
    id: 13,
    word: 'إياك',
    translation: 'You alone',
    type: 'pronoun',
    example: "Iyyaka na'budu.",
  },
  {
    id: 14,
    word: 'نعبد',
    translation: 'We worship',
    type: 'verb',
    example: 'We worship You alone.',
  },
  {
    id: 15,
    word: 'وإياك',
    translation: 'And You alone',
    type: 'pronoun',
    example: "Wa iyyaka nasta'in.",
  },
  {
    id: 16,
    word: 'نستعين',
    translation: 'We seek help',
    type: 'verb',
    example: 'In You alone we seek aid.',
  },
  {
    id: 17,
    word: 'اهدنا',
    translation: 'Guide us',
    type: 'verb',
    example: 'Ihdina al-sirat al-mustaqeem.',
  },
  {
    id: 18,
    word: 'الصراط',
    translation: 'The path',
    type: 'noun',
    example: 'The straight way.',
  },
  {
    id: 19,
    word: 'المستقيم',
    translation: 'The straight',
    type: 'adjective',
    example: 'The path that is straight and correct.',
  },
  {
    id: 20,
    word: 'صراط',
    translation: 'Path',
    type: 'noun',
    example: 'Path of those blessed.',
  },
  {
    id: 21,
    word: 'الذين',
    translation: 'Of those who',
    type: 'relative pronoun',
    example: 'Those upon whom grace was bestowed.',
  },
  {
    id: 22,
    word: 'أنعمت',
    translation: 'You have bestowed favour',
    type: 'verb',
    example: 'You granted favours upon them.',
  },
  {
    id: 23,
    word: 'عليهم',
    translation: 'Upon them',
    type: 'prepositional phrase',
    example: 'Grace is upon them.',
  },
  {
    id: 24,
    word: 'غير',
    translation: 'Not',
    type: 'preposition',
    example: 'Ghayril maghdubi.',
  },
  {
    id: 25,
    word: 'المغضوب',
    translation: 'Those who earned anger',
    type: 'noun',
    example: 'Those who were condemned.',
  },
  {
    id: 26,
    word: 'عليهم',
    translation: 'Upon them',
    type: 'prepositional phrase',
    example: 'Anger upon them.',
  },
  {
    id: 27,
    word: 'ولا',
    translation: 'Nor',
    type: 'conjunction',
    example: 'Nor those who went astray.',
  },
  {
    id: 28,
    word: 'الضالين',
    translation: 'Those who went astray',
    type: 'noun',
    example: 'Those who deviated from guidance.',
  },
];

export default arabicWordInfo;
