import { Surah } from 'types/Surah';
import { ListItemDataProp } from 'types/ListItemProps';

export const listOfChapters: ListItemDataProp[] = [
  {
    number: 1,
    name: 'Al-Fatihah',
    arabicName: 'الفاتحة',
    revelationType: 'Meccan',
    numOfVerses: 7,
    translation: 'The Opening',
  },
  {
    number: 2,
    name: 'Al-Baqarah',
    arabicName: 'البقرة',
    revelationType: 'Medinan',
    numOfVerses: 286,
    translation: 'The Cow',
  },
  {
    number: 3,
    name: 'Aal-i-Imran',
    arabicName: 'آل عمران',
    revelationType: 'Medinan',
    numOfVerses: 200,
    translation: 'The Family of Imran',
  },
  {
    number: 4,
    name: 'An-Nisa',
    arabicName: 'النساء',
    revelationType: 'Medinan',
    numOfVerses: 176,
    translation: 'The Women',
  },
  {
    number: 5,
    name: "Al-Ma'idah",
    arabicName: 'المائدة',
    revelationType: 'Medinan',
    numOfVerses: 120,
    translation: 'The Table Spread',
  },
  {
    number: 6,
    name: "Al-An'am",
    arabicName: 'الأنعام',
    revelationType: 'Meccan',
    numOfVerses: 165,
    translation: 'The Cattle',
  },
  {
    number: 7,
    name: "Al-A'raf",
    arabicName: 'الأعراف',
    revelationType: 'Meccan',
    numOfVerses: 206,
    translation: 'The Heights',
  },
  {
    number: 8,
    name: 'Al-Anfal',
    arabicName: 'الأنفال',
    revelationType: 'Medinan',
    numOfVerses: 75,
    translation: 'The Spoils of War',
  },
  {
    number: 9,
    name: 'At-Tawbah',
    arabicName: 'التوبة',
    revelationType: 'Medinan',
    numOfVerses: 129,
    translation: 'The Repentance',
  },
  {
    number: 10,
    name: 'Yunus',
    arabicName: 'يونس',
    revelationType: 'Meccan',
    numOfVerses: 109,
    translation: 'Jonah',
  },
  {
    number: 11,
    name: 'Hud',
    arabicName: 'هود',
    revelationType: 'Meccan',
    numOfVerses: 123,
    translation: 'Hud',
  },
  {
    number: 12,
    name: 'Yusuf',
    arabicName: 'يوسف',
    revelationType: 'Meccan',
    numOfVerses: 111,
    translation: 'Joseph',
  },
  {
    number: 13,
    name: "Ar-Ra'd",
    arabicName: 'الرعد',
    revelationType: 'Medinan',
    numOfVerses: 43,
    translation: 'The Thunder',
  },
  {
    number: 14,
    name: 'Ibrahim',
    arabicName: 'إبراهيم',
    revelationType: 'Meccan',
    numOfVerses: 52,
    translation: 'Abraham',
  },
  {
    number: 15,
    name: 'Al-Hijr',
    arabicName: 'الحجر',
    revelationType: 'Meccan',
    numOfVerses: 99,
    translation: 'The Rocky Tract',
  },
  {
    number: 16,
    name: 'An-Nahl',
    arabicName: 'النحل',
    revelationType: 'Meccan',
    numOfVerses: 128,
    translation: 'The Bee',
  },
  {
    number: 17,
    name: 'Al-Isra',
    arabicName: 'الإسراء',
    revelationType: 'Meccan',
    numOfVerses: 111,
    translation: 'The Night Journey',
  },
  {
    number: 18,
    name: 'Al-Kahf',
    arabicName: 'الكهف',
    revelationType: 'Meccan',
    numOfVerses: 110,
    translation: 'The Cave',
  },
  {
    number: 19,
    name: 'Maryam',
    arabicName: 'مريم',
    revelationType: 'Meccan',
    numOfVerses: 98,
    translation: 'Mary',
  },
  {
    number: 20,
    name: 'Ta-Ha',
    arabicName: 'طه',
    revelationType: 'Meccan',
    numOfVerses: 135,
    translation: 'Ta-Ha',
  },
  {
    number: 21,
    name: 'Al-Anbiya',
    arabicName: 'الأنبياء',
    revelationType: 'Meccan',
    numOfVerses: 112,
    translation: 'The Prophets',
  },
  {
    number: 22,
    name: 'Al-Hajj',
    arabicName: 'الحج',
    revelationType: 'Medinan',
    numOfVerses: 78,
    translation: 'The Pilgrimage',
  },
  {
    number: 23,
    name: "Al-Mu'minun",
    arabicName: 'المؤمنون',
    revelationType: 'Meccan',
    numOfVerses: 118,
    translation: 'The Believers',
  },
  {
    number: 24,
    name: 'An-Nur',
    arabicName: 'النور',
    revelationType: 'Medinan',
    numOfVerses: 64,
    translation: 'The Light',
  },
  {
    number: 25,
    name: 'Al-Furqan',
    arabicName: 'الفرقان',
    revelationType: 'Meccan',
    numOfVerses: 77,
    translation: 'The Criterion',
  },
  {
    number: 26,
    name: "Ash-Shu'ara",
    arabicName: 'الشعراء',
    revelationType: 'Meccan',
    numOfVerses: 227,
    translation: 'The Poets',
  },
  {
    number: 27,
    name: 'An-Naml',
    arabicName: 'النمل',
    revelationType: 'Meccan',
    numOfVerses: 93,
    translation: 'The Ant',
  },
  {
    number: 28,
    name: 'Al-Qasas',
    arabicName: 'القصص',
    revelationType: 'Meccan',
    numOfVerses: 88,
    translation: 'The Stories',
  },
  {
    number: 29,
    name: 'Al-Ankabut',
    arabicName: 'العنكبوت',
    revelationType: 'Meccan',
    numOfVerses: 69,
    translation: 'The Spider',
  },
  {
    number: 30,
    name: 'Ar-Rum',
    arabicName: 'الروم',
    revelationType: 'Meccan',
    numOfVerses: 60,
    translation: 'The Romans',
  },
];
// Sample data - replace with your actual data source
export const SAMPLE_SURAHS: readonly Surah[] = [
  { id: 1, number: 1, name: 'Al-Fatiha', nameArabic: 'الفاتحة', verses: 7 },
  { id: 2, number: 2, name: 'Al-Baqarah', nameArabic: 'البقرة', verses: 286 },
  { id: 3, number: 3, name: 'Ali Imran', nameArabic: 'آل عمران', verses: 200 },
  { id: 4, number: 4, name: 'An-Nisa', nameArabic: 'النساء', verses: 176 },
  { id: 5, number: 5, name: 'Al-Maidah', nameArabic: 'المائدة', verses: 120 },
  { id: 6, number: 6, name: 'Al-Anam', nameArabic: 'الأنعام', verses: 165 },
  { id: 7, number: 7, name: 'Al-Araf', nameArabic: 'الأعراف', verses: 206 },
  { id: 8, number: 8, name: 'Al-Anfal', nameArabic: 'الأنفال', verses: 75 },
  { id: 9, number: 9, name: 'At-Tawbah', nameArabic: 'التوبة', verses: 129 },
  { id: 10, number: 10, name: 'Yunus', nameArabic: 'يونس', verses: 109 },
] as const;
